version: 2

models:
  - name: int_customer_payments
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: int_active_subscriptions
    columns:
      - name: subscription_id
        tests:
          - unique
          - not_null

  - name: int_monthly_revenue
    columns:
      - name: payment_month
        tests:
          - not_null

  - name: int_customer_cohorts
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
