version: 2

sources:
  - name: raw
    database: ecommerce_analytics
    schema: raw
    description: "Raw Stripe payment and subscription data"
    
    tables:
      - name: raw_customers
        description: "Customer master data"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
            tests:
              - unique
              - not_null
          - name: email
            tests:
              - not_null
          - name: created_at
            description: "Customer signup timestamp"
            tests:
              - not_null
      
      - name: raw_products
        description: "Subscription product catalog"
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
          - name: product_name
            tests:
              - not_null
          - name: price
            tests:
              - not_null
      
      - name: raw_subscriptions
        description: "Subscription lifecycle data"
        columns:
          - name: subscription_id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
      
      - name: raw_payments
        description: "Payment transaction records"
        columns:
          - name: payment_id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - not_null
          - name: amount
            tests:
              - not_null
      
      - name: raw_invoices
        description: "Invoice records"
        columns:
          - name: invoice_id
            tests:
              - unique
              - not_null